#!/usr/local/bin/perl

#  Copyright 2008, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id$
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CM

#
#
# Function create a random file name based on the current time.
#
# Notes: Function will create a temporary directory where the file name will be written to
#        based on the current time.
#
#        The format of the directory and file name is:
#
#        $SCRATCH_AREA/current_logs/__$ENV{RANDOM_NUMBER}.$i_datasource/tmp_$i_partial_name
#
# Assumption:
#
#   1) Environment variable SCRATCH_AREA is defined.
#   2) Process has write permission on $SCRATCH_AREA and $SCRATCH_AREA/current_logs/
#
#------------------------------------------------------------------------------------------------

do "$GHRSST_PERL_LIB_DIRECTORY/actualize_directory.pl";

sub create_random_filename {

    # Returned status.  Value of 0 means ok, 1 means bad.

    my $o_random_name = "";

    #
    # Get input(s).
    #
    
    my $i_datasource        = lc($_[0]);
    my $i_partial_name      =    $_[1];

    #
    # Local variables.
    #

    my $TEMPORARY_PREFIX = "tmp_";  # This string will prefix every file name returned.
    my $RUN_LOGS_DIR     = "current_logs";  # Directory sub to scratch_area will be created.
    my $scratch_area     = $ENV{SCRATCH_AREA}; 
    my $log_dir          = $scratch_area . "/" . $RUN_LOGS_DIR;
    my $processing_directory = $log_dir . "/" . "__" . $ENV{RANDOM_NUMBER}
                               . "." . $i_datasource;

    # The name to return is the processing_directory plus whatever strings provided by the user.

    my $o_random_name = $processing_directory . "/" . $TEMPORARY_PREFIX . $i_partial_name;

    # Create director(ies) if they don't exist already.
    my $l_actualize_status = 0;
    $l_actualize_status = actualize_directory($scratch_area);
    $l_actualize_status = actualize_directory($log_dir);
    $l_actualize_status = actualize_directory($processing_directory);

    # ---------- Close up shop ----------
    return ($o_random_name);

} # end sub create_random_filename
