#!/usr/local/bin/perl

#  Copyright 2008, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id$
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CM

#
# Function answers a 3 fold question:
#
#   1. Does this MODIS L2P occurs in registry?
#   2. Does it exist on file system?
#   3. Is it being staged but not processed right now?
#
# If anyone of the conditions is true return 1, else return 0;
#
# Assumption:
#
#   1) TBD
#
#------------------------------------------------------------------------------------------------

do "$GHRSST_PERL_LIB_DIRECTORY/has_file_been_processed_before.pl";
do "$GHRSST_PERL_LIB_DIRECTORY/is_file_being_processed.pl";
do "$GHRSST_PERL_LIB_DIRECTORY/has_file_had_processing_error_before.pl";

sub does_file_exist_in_registry_or_filesystem {

    # Returned variable.

    my $r_file_existed_already = 0;

    #
    # Get input.
    #
    
    my $i_L2P_registry             = shift; # Name of registry.
    my $i_scratch_area             = shift; # Directory where registry is stored. 
    my $i_compress_flag            = shift; # Whether the file will be compressed or not.
    my $i_output_l2p_core_filename = shift; # Full pathname of output file.
    my $i_l2p_core_filename_only   = shift; # File name only.
    my $i_processing_type          = shift; # QUICKLOOK or REFINED

    my $debug_flag = 0;

    # If the file is to be compressed, we look for file name like .bz2.

    if ($i_compress_flag eq "yes") {
            #
            # The compressed file has .bz2 extension.  Must add this before checking for file
            # existence if the user wants to compress the file at the end.
            #

            my $l_l2p_core_filename_only   = "";
            
            # Only look for the .bz2 file is processing GDS1 format.
            if ($ENV{CREATE_MODIS_L2P_IN_GDS2_FORMAT} ne 'true') {
                $l_l2p_core_filename_only  = $i_l2p_core_filename_only . ".bz2"; 
            } else {
                # The GDS2 format is not compressed.
                $l_l2p_core_filename_only  = $i_l2p_core_filename_only; 
            }

            # Check in processed file registry.
            if (has_file_been_processed_before($i_scratch_area,
                                               $i_L2P_registry,
                                               $l_l2p_core_filename_only)) {
                if ($debug_flag) {
                    print "does_file_exist_in_registry_or_filesystem: $l_l2p_core_filename_only FILE_L2P_PROCESSED_BEFORE\n"; 
                }
                $r_file_existed_already = 1; 
            }
            if ($debug_flag) {
                print "does_file_exist_in_registry_or_filesystem: after has_file_been_processed_before, r_file_existed_already = $r_file_existed_already\n";
            }

            # Check in Error File Registry.
            # Note, we use the name without the .bz2 extension.
            if (has_file_had_processing_error_before($i_processing_type,
                                                     $i_l2p_core_filename_only)) {
                if ($debug_flag) {
                    print "does_file_exist_in_registry_or_filesystem: $l_l2p_core_filename_only FILE_L2P_HAD_PROCESSING_ERROR\n";
                }
                $r_file_existed_already = 1; 
            }

            if ($debug_flag) {
                print "does_file_exist_in_registry_or_filesystem: after has_file_had_processing_error_before, $l_l2p_core_filename_only r_file_existed_already = $r_file_existed_already\n";
            }

            # Check on file system.
            my $name_with_bzip_extension =  $i_output_l2p_core_filename . ".bz2";
            if (-e $name_with_bzip_extension) {
                $r_file_existed_already = 1; 
                if ($debug_flag) {
                    print "does_file_exist_in_registry_or_filesystem: $name_with_bzip_extension FILE_L2P_ON_FILE_SYSTEM\n";
                }
            }
            if ($debug_flag) {
                print "does_file_exist_in_registry_or_filesystem: after file_system_check, l_l2p_core_filename_only r_file_existed_already = $r_file_existed_already\n";
            }

            # Check on "current_jobs" directory.

            if (is_file_being_processed($i_scratch_area,
                                        $l_l2p_core_filename_only)) {
                $r_file_existed_already = 1; 
                if ($debug_flag) {
                    print "does_file_exist_in_registry_or_filesystem: $l_l2p_core_filename_only FILE_L2P_IS_BEING_PROCESSED\n";
                }
            }
            if ($debug_flag) {
                print "does_file_exist_in_registry_or_filesystem: after is_file_being_processed, $l_l2p_core_filename_only r_file_existed_already = $r_file_existed_already\n";
            }

    } else { 
            #
            # The un-compressed file does not have .bz2 extension just the normal .nc extension.
            # Check for existence of the name as is.
            #

            # Check on file system.
            if (-e $i_output_l2p_core_filename) {
                $r_file_existed_already = 1; 
                if ($debug_flag) {
                    print "does_file_exist_in_registry_or_filesystem: $i_output_l2p_core_filename FILE_L2P_ON_FILE_SYSTEM\n";
                }
            }
    }

    if ($debug_flag) {
        print "does_file_exist_in_registry_or_filesystem: before return, r_file_existed_already = $r_file_existed_already\n";
    }
    return ($r_file_existed_already);
}
