#! /usr/local/bin/perl

#  Copyright 2005, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id: has_file_been_processed_before.pl,v 1.3 2007/08/08 15:04:12 qchau Exp $
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CVS
# New Request #xxxx

# Subroutine returns 1 if the name to check appears in master processed file, 0 else.
#
#------------------------------------------------------------------------------------------------

sub has_file_been_processed_before {

    #
    # Get input.
    #

    my $i_scratch_area                  = $_[0];
    my $i_master_processed_filelist     = $_[1];
    my $i_filename_to_check             = $_[2];

    #
    # Returned variable(s).
    #
    
    my $r_file_processed = 0;

    # Get the number of lines containing the i_filename_to_check

    my @wc_line = ();
    @wc_line = readpipe("grep -c -e $i_filename_to_check $i_master_processed_filelist");

    # Remove trailing blanks and all blanks between.

    chomp($wc_line[0]);
    $wc_line[0] =~ s/ //g;

#print "$i_filename_to_check wc_line[0] = $wc_line[0]\n";
    if ($wc_line[0] eq "0") {
        $r_file_processed = 0;
    } else {
        $r_file_processed = 1;
    }

#    print "has_file_been_processed_before: i_filename_to_check = $i_filename_to_check\n";
#    print "has_file_been_processed_before: r_file_processed = $r_file_processed\n";

    return ($r_file_processed);
}
