#!/usr/local/bin/perl
#
#  Copyright 2007, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id: is_file_being_processed.pl,v 1.1 2007/08/08 15:04:12 qchau Exp $
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CM

# Subroutine returns 1 if the file is either waiting to be processed or running.
# Returns 0 otherwise.
#
#------------------------------------------------------------------------------------------------

sub is_file_being_processed {

    #
    # Get input.
    #

    my $i_scratch_area                  = shift; 
    my $i_filename_to_check             = shift; 

    #
    # Returned variable(s).
    #
    
    my $r_file_is_processing = 0;

    # If the file is being processed, there will be a file name in the current_jobs/ directory
    # beneath the scratch directory.

    my $l_fullname_to_check = $i_scratch_area . "/current_jobs/" . $i_filename_to_check;

#print "is_file_being_processed: l_fullname_to_check = $l_fullname_to_check\n";

    if (-e $l_fullname_to_check) {
        $r_file_is_processing = 1;
    }

#    print "is_file_being_processed: i_filename_to_check = $i_filename_to_check\n";
#    print "is_file_being_processed: r_file_is_processing = $r_file_is_processing\n";

    return ($r_file_is_processing);
}
