#!/usr/local/bin/perl

#  Copyright 2007, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id: perform_modis_temporary_files_cleanup.pl,v 1.2 2007/05/01 17:39:41 qchau Exp $
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CM

#
#
# Subroutine removes temporary files created during MODIS processing.
#
# Assumption:
#
#   1) TBD 
#
#------------------------------------------------------------------------------------------------

sub perform_modis_temporary_files_cleanup {


    # Returned status.  Value of 0 means ok, 1 means bad.

    my $o_status = 0;

    #
    # Get input.
    #
    
    my $tmp_idl_batch_file               = shift;
    my $tmp_filelist                     = shift;
    my $tmp_doy_filelist                 = shift;
    my $tmp_one_day_filelist             = shift;
    my $tmp_uncompressed_bzip_filelist   = shift;
    my $tmp_processed_datasets_status    = shift;

    #
    # Clean up.
    #

#print "unlink[$tmp_idl_batch_file]\n";
#print "unlink[$tmp_filelist]\n";
#print "unlink[$tmp_doy_filelist]\n";
#print "unlink[$tmp_one_day_filelist]\n";
#print "unlink[$tmp_uncompressed_bzip_filelist]\n";
#print "unlink[$tmp_processed_datasets_status]\n";

    if (-e $tmp_idl_batch_file)             { unlink($tmp_idl_batch_file); }
    if (-e $tmp_filelist)                   { unlink($tmp_filelist); }
    if (-e $tmp_doy_filelist)               { unlink($tmp_doy_filelist); }
    if (-e $tmp_one_day_filelist)           { unlink($tmp_one_day_filelist); }
    if (-e $tmp_uncompressed_bzip_filelist) { unlink($tmp_uncompressed_bzip_filelist); }
    if (-e $tmp_processed_datasets_status)  { unlink($tmp_processed_datasets_status); }

    # ---------- Close up shop ----------
    return ($o_status);

} # end sub perform_modis_temporary_files_cleanup 
