#!/usr/local/bin/perl

#  Copyright 2007, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id: remove_refined_prefix_from_filename.pl,v 1.2 2007/12/04 22:09:40 qchau Exp $
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CVS

# Subroutine removes the "refined_" prefix from a MODIS filename and returned a "smaller" name.
#
# Assumption:
#   1) The name does not have a directory prefix.
#
#------------------------------------------------------------------------------------------------

sub remove_refined_prefix_from_filename {

    #
    # Get input.
    #

    my $i_filename = $_[0];

    #
    # Local variables.
    #
    
    my $r_status = 0;
    my $r_filename = $i_filename;  # Assumed name is un-changed. 

    #
    # The filename has the below format:
    #
    #    A2006097005500.L2_LAC_GSSTN.bz2
    #
    #     01234567890
    #

    #
    # The REFINED datasets have the "refined_" prefix.  If the name contains the "refined_" prefix,
    # remove it.
    #

#print "remove_refined_prefix_from_filename:BEFORE i_filename= $i_filename\n";
    my $REFINED_DATASET_PREFIX_SUBSTR = "refined_";
    my $OFFSET_AFTER_REFINED_SUBSTR = length($REFINED_DATASET_PREFIX_SUBSTR);
    my $refined_prefix_pos = index($i_filename,$REFINED_DATASET_PREFIX_SUBSTR);

    #
    # Skip the prefix.
    #

    if ($refined_prefix_pos == 0) {
        # Combine the substring together to form a complete new name.
        $r_filename = substr($i_filename,$OFFSET_AFTER_REFINED_SUBSTR); 
    }

#print "refined_prefix_pos = $refined_prefix_pos\n";
#print "remove_refined_prefix_from_filename:AFTER r_filename = $r_filename\n";

    #
    # Close up shop and return.
    #

    return ($r_status,
            $r_filename);
}
