#!/usr/local/bin/perl

#  Copyright 2008, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id$
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CM

# Subroutine create a directory if it does not exist already.

#------------------------------------------------------------------------------------------------

sub actualize_directory {

    #
    # Get input.
    #

    my $i_directory_name = $_[0];

    #
    # Local variables.
    #
    
    my $r_status = 0;

    # Create the directory if it doesn't exist already. 

    if (!(-e $i_directory_name)) {
#print "actualize_directory: creating directory [$i_directory_name]\n";
        mkdir($i_directory_name);
    } else {
#print "actualize_directory: exist directory [$i_directory_name]\n";
    }

    #
    # Close up shop and return.
    #

    return ($r_status)
}
