#! /usr/local/bin/perl

#  Copyright 2005, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id: create_modis_l2p_core_output_structure.pl,v 1.2 2006/05/27 00:28:15 qchau Exp $
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CVS
# New Request #xxxx

# Subroutine parses a MODIS sea surface temperature file name for the start time
# Certain assumptions are made about the format of the filename.
#
#------------------------------------------------------------------------------------------------

sub create_modis_l2p_core_output_structure {

    #
    # Get input.
    #

    my $i_l2p_core_output_directory = $_[0];
    my $i_yyyy         = $_[1];
    my $i_doy          = $_[2];

    #
    # Local variables.
    #
    
    my $r_status = 0;
    my $mode_mask = 0775;  # Same as chmod u+rw g+rw o+r 

    # Create the year directory if it doesn't exist already. 

    my $directory_with_year = "$i_l2p_core_output_directory/$i_yyyy";

    if (-e $directory_with_year) {
#print "create_modis_l2p_core_output_structure: Directory exists: $i_yyyy\n";
#print "create_modis_l2p_core_output_structure: sub to          : $i_l2p_core_output_directory\n";
#print "create_modis_l2p_core_output_structure: Do nothing.\n";
    } else {
print "create_modis_l2p_core_output_structure: Creating directory: $directory_with_year\n";
        mkdir($directory_with_year,$mode_mask);
    }

    # Create the doy directory if it doesn't exist already. 
  
    my $directory_with_doy = "$directory_with_year/$i_doy";

    if (-e $directory_with_doy) {
#print "create_modis_l2p_core_output_structure: Directory exists: $i_doy\n";
#print "create_modis_l2p_core_output_structure: sub to          : $directory_with_year\n";
#print "create_modis_l2p_core_output_structure: Do nothing.\n";
    } else {
print "create_modis_l2p_core_output_structure: Creating directory: $directory_with_doy\n";
        mkdir($directory_with_doy,$mode_mask);
    }

    #
    # Close up shop and return.
    #

    return ($r_status)
}
