#!/usr/local/bin/perl
#
#  Copyright 2008, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id$
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CM

# Subroutine appends an entry to the Error File Registry (EFR) reporting
# the name of the file in question, when the error occured, and the reason.
#
# The types of error that can occured are:
#
#    File is corrupted
#    File is not found
#
#------------------------------------------------------------------------------------------------

do "$GHRSST_PERL_LIB_DIRECTORY/get_error_file_registry_filename.pl";

sub report_error_to_error_file_registry {

    #
    # Get input.
    #

    my $i_processing_type   = uc(shift); 
    my $i_l2p_core_filename = shift; 
    my $i_reason            = shift; 

    #
    # Local variables.
    #
    
    my $r_status = 0;

    # Determine which EFR to use depends on the processing type.

    my $l_error_file_registry_filename = get_error_file_registry_filename($i_processing_type);
 
    if ($l_error_file_registry_filename eq "") {
        print "report_error_to_error_file_registry.pro - ERROR: File name is empty string.";
        $r_status = 1;
        return($r_status);
    }

    # Create an empty file if it does not exist already.

    if (!(-e $l_error_file_registry_filename)) {
        print "report_error_to_error_file_registry.pro - INFO: No file error registry exist yet.  Creating an empty one [$l_error_file_registry_filename]\n";
        system("touch $l_error_file_registry_filename");
    }

    # Get the system time in seconds since 1970 and ascii time.
    my $seconds_since_1970 = time();
    my $ascii_date         = localtime($seconds_since_1970); 

    # Build the entry line.
    my $entry_line = "$i_l2p_core_filename,$seconds_since_1970,$ascii_date,$i_reason";

    #print "command line = [echo \"$entry_line\" >> $l_error_file_registry_filename\n";

    # Perform the append.
    print "report_error_to_error_file_registry.pro - ERROR: Adding entry [$entry_line] to EFR file [$l_error_file_registry_filename]\n";
    system("echo \"$entry_line\" >> $l_error_file_registry_filename");

    #

    return ($r_status);
}
